fprintf("PC: %04X A: %02X X: %02X Y: %02X S: %02X P: %02X (%c%c%c%c%c%c) OPC: %02X\n", ...
    pc, a, x, y, s, p, ...
    (bitand(p, 0x80) > 0) * ('N' - '-') + '-', ...
    (bitand(p, 0x02) > 0) * ('Z' - '-') + '-', ...
    (bitand(p, 0x01) > 0) * ('C' - '-') + '-', ...
    (bitand(p, 0x04) > 0) * ('I' - '-') + '-', ...
    (bitand(p, 0x08) > 0) * ('D' - '-') + '-', ...
    (bitand(p, 0x40) > 0) * ('V' - '-') + '-', ...
    b);

pause(.05)
